# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldStats
                                 A QGIS plugin
 Generate basic statistic for numeric and text field in a vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-17
        copyright            : (C) 2018 by Orden Aitchedji, Mckenna Duzac, Andreas Foulk, Tanner Lee
        email                : afoulk@mines.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FieldStats class from file FieldStats.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fs_3 import FieldStats
    return FieldStats(iface)
